config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :subscriptions
  resources :comments
  devise_for :users
  resources :users
  root "events#index"

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :event
  belongs_to :user

  validates :event, presence: true

  validates :user_name, presence: true, unless: -> { user.present? }
  validates :user_email, presence: true, format: /\A[a-zA-Z0-9\-_.]+@[a-zA-Z0-9\-_.]+\z/, unless: -> { user.present? }

  validates :user, uniqueness: {scope: :event_id}, if: -> { user.present? }

  validates :user_email, uniqueness: {scope: :event_id}, unless: -> { user.present? }

  def user_name
    if user.present?
      user.name
    else
      super
    end
  end

  def user_email
    if user.present?
      user.email
    else
      super
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_event, only: [:create, :destroy]
  before_action :set_subscription, only: [:destroy]
  before_action :check_disabled_email, only: [:create]

  def create
    @new_subscription = @event.subscriptions.build(subscription_params)
    @new_subscription.user = current_user

    if @new_subscription.save
      EventMailer.subscription(@event, @new_subscription).deliver_now
      redirect_to @event, notice: I18n.t('controllers.subscriptions.created')
    else
      render 'events/show', alert: I18n.t('controllers.subscriptions.error')
    end
  end

  def destroy
    message = {notice: I18n.t('controllers.subscriptions.destroyed')}

    if current_user_can_edit?(@subscription)
      @subscription.destroy
    else
      message = {alert: I18n.t('controllers.subscriptions.error')}
    end

    redirect_to @event, message
  end

  private

  def check_disabled_email
    if current_user.nil? && User.find_by(email: subscription_params[:user_email])
      redirect_to @event, alert: I18n.t('controllers.subscriptions.error')
    end
  end

  def set_subscription
    @subscription = @event.subscriptions.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

  def subscription_params
    params.fetch(:subscription, {}).permit(:user_email, :user_name)
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for [@event, subscription] do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: subscription} %>

  <% unless user_signed_in? %>
    <div class="form-group">
      <%= f.label :user_name %>
      <%= f.text_field :user_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :user_email %>
      <%= f.text_field :user_email, class: 'form-control' %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit 'Подписаться', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/subscriptions/_subscription.html.erb
<span class="subscription">
  <% if subscription.user.present? %>
    <%= render partial: 'users/user', object: subscription.user %>
  <% else %>
    <em><%= subscription.user_name %></em>
  <% end %>
  <% if current_user_can_edit?(subscription) %>
    <%= link_to((fa_icon 'times'), event_subscription_path(subscription.event, subscription), method: :delete, data: {confirm: t('.destroy_confirm')}) %>
  <% end %>
</span>